@startuml a

class Dipendente {
    +nome : str
    +stipendio: int

    __
    +def __init__(self,nome,stipendio)


}
class Manager {
     +nome : str
     +stipendio: int
     +numero_di_team : int 
     __
     +def Get_num_team(self)
     +def Get_nome(self)
     +def Get_stipendio(self)


}
class Developer {
     +nome : str
     +stipendio: int
     +codice : str 
     __
     +def Get_num_team(self)
     +def Get_nome(self)
     +def def Get_Codice(self)
}

    


Manager <|-- Dipendente
Developer <|-- Dipendente

@enduml