@startuml a

class Pagamento {
    +Nome : str
    +Codice : int 
    +Data :int 
    +Pin : int 
    +Email 
    +Password 

    __
    +def processa_pagamento()

}
class CartadiCredito {
     +Nome : str
     +Codice : int 
     +Data :int 
     +Pin : int 
     __
     +def processa_pagamento()

}
class PayPal {
     +Email
     +Password
     __
     +def processa_pagamento()
}

    


Pagamento<|-- CartadiCredito
Pagamento <|-- PayPal

@enduml